language: php

php:
  - 5.6
  - 7.0

before_script:
  - "mkdir -p ~/.composer"
  - openssl aes-256-cbc -K $encrypted_43170733c148_key -iv $encrypted_43170733c148_iv -in .travis.composer.config.json.enc -out ~/.composer/config.json -d
  - composer self-update
  - composer install
  - composer require satooshi/php-coveralls:dev-master

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/coveralls
