language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1
    - php: nightly

before_install:
  - "mkdir -p ~/.composer"
  - openssl aes-256-cbc -K $encrypted_43170733c148_key -iv $encrypted_43170733c148_iv -in .travis.composer.config.json.enc -out ~/.composer/config.json -d

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-text

after_success:
  - composer require satooshi/php-coveralls
  - vendor/bin/coveralls
